from typing import List, Optional, TypedDict

class AgentState(TypedDict):
    # Workflow's shared state

    topic: str                          # Original topic of the conversation
    outline: Optional[str]              # Outline of the content to be generated by planner agent
    research_data: Optional[List[str]]  # Data collected by the researcher agent
    draft: Optional[str]                # Draft created by the writer agent
    feedback: Optional[str]             # Feedback provided by the reviewer agent
    revision_number: int                # Number of revisions made
    decision: Optional[str]             # Decision made by the reviewer ("approve" or "revise")
    final_content: Optional[str]        # Final context after all revisions

    
